### ISSUE TITLE
abort(CompileError: wasm validation error: at offset 4: failed to match magic number). Build with -s ASSERTIONS=1 for more info.

### ISSUE THREAD

**Issue by ikariiin** [skiptirengu/anitomyscript#7]
Error reproduction: https://codesandbox.io/s/laughing-pike-xf1wi

Get the same error but with a bit of extra information while running the same sort of code in an electron app,
```
RuntimeError: abort(CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0). Build with -s ASSERTIONS=1 for more info.
```
![image](https://user-images.githubusercontent.com/10518541/86427653-5adc5a80-bd08-11ea-8978-2da2586e9e9e.png)

**Comment by sugiruu** [comment]
Are you using webpack or some kind of bundler on the electron app?

**Comment by ikariiin** [comment]
Yes I'm using webpack for bundling.

**Comment by sugiruu** [comment]
OK, it seems webpack (or most bundlers) do not play along very well with emscripten due to how the internal implementation of the `.wasm` loader works.

Making this lib compatible with bundlers will require some work, which I do not have the time for right now, but I'll do it eventually. For now, I'd suggest you to either:
- Use the version `1.x` which uses asm.js backend;
- Or use [anitomy-js](https://github.com/skiptirengu/anitomy-js).

**Comment by ikariiin** [comment]
Alrighty, that makes a fair bit of sense. Thanks for looking into it. 

Also really appreciate you porting this library <3.
